### ISSUE TITLE
Error after migrating to postcss-next

### ISSUE THREAD

**Issue by 0x80** [jonathantneal/postcss-nesting#12]
I don't know how this is related but since I tried migrating from cssnext to postcss-cssnext I'm getting the following error from postcss-nesting when building with webpack:

```javascript
ModuleBuildError: Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'forEach' of undefined
    at transpileSelectors (/Users/me/myproject/node_modules/postcss-nesting/index.js:71:20)
    at /Users/me/myproject/node_modules/postcss-nesting/index.js:57:4
```

Here is my webpack config

```javascript
postcss: function (webpack) {
    return [
      require('autoprefixer')({
        browsers: 'last 2 versions',
        remove: false // faster if not processing legacy css
      }),
      require('postcss-import')({
        path: path.join(__dirname, 'app'),
        addDependencyTo: webpack, // for HMR
        glob: true
      }),
      require('postcss-url')(),
      require('postcss-cssnext')(),
      require('postcss-mixins')(),
      require('postcss-nesting')(),
      require('postcss-browser-reporter')(),
      require('postcss-reporter')()
    ]
  },
```

And it is coming from this css file, which used to work fine before
```css3
@import 'variables/all';
@import 'mixins/verticalCenter';

:root {
  --button-height: 2.5em;
  --button-padding: 2em;
}

@define-mixin buttonCommon {
  white-space: nowrap;
  padding: 0;
  height: var(--button-height);
  text-transform: uppercase;
  color: var(--color-white);
  background-color: var(--color-gray);
  border: none;
  /*border-radius: var(--radius-circle);*/
  transition-property: color, background-color, border, transform;
  transition-duration: var(--transition-duration-s);
  -webkit-tap-highlight-color: transparent;
  -webkit-appearance: none;
  &:focus {
    outline: none;
  }

  &:disabled {
    background: var(--color-gray);
    color: var(--color-white);
  }

  width: 10em; /* todo find way to not stretch in flexbox */
}

.main {
  @mixin buttonCommon;
}

.content {
  @mixin verticalCenter;
  font-size: var(--font-size-l);
  /*font-weight: var(--font-weight-medium);*/
  margin-left: var(--button-padding);
  margin-right: var(--button-padding);
}

.isPrimary {
  background-color: var(--color-green);

  &:active {
    color: var(--color-gray);
  }
}

.isSecondary {
  background-color: var(--color-blue);

  &:active {
    color: var(--color-gray);
  }
}
```

**Comment by MoOx** [comment]
postcss-nesting is already in postcss-cssnext.

**Comment by MoOx** [comment]
Same thing for autoprefixer.
You should use this

```js
  postcss: function (webpack) {
    return [
      require('postcss-import')({
        path: path.join(__dirname, 'app'),
        addDependencyTo: webpack, // for HMR
        glob: true
      }),
      require('postcss-url')(),
      require('postcss-cssnext')({
        browsers: 'last 2 versions',
        features: {
          autoprefixer: {
            remove: false // faster if not processing legacy css
          }
        }
      }),
      require('postcss-mixins')(),
      require('postcss-browser-reporter')(),
      require('postcss-reporter')()
    ]
  },
```

**Comment by 0x80** [comment]
Ah ok! But now when I remove the plugin I still get the same error. This one's from the dev server:

```
ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[name]--[local]--[hash:base64:5]!./~/postcss-loader!./app/styles/Button.css
Module build failed: TypeError: Cannot read property 'forEach' of undefined
```

**Comment by MoOx** [comment]
Can you track down the CSS involved?

**Comment by 0x80** [comment]
Yes I will try!

**Comment by 0x80** [comment]
Weird. It seems to be this part:

```
&:focus {
    outline: none;
  }

  &:disabled {
    background: var(--color-gray);
    color: var(--color-white);
  }
```

If I enable either one of those selectors inside the buttonCommon mixin it goes wrong

**Comment by MoOx** [comment]
Maybe showing the parent selector might help.

**Comment by 0x80** [comment]
Not sure what you mean. It is part of the @define-mixin buttonCommon in the css I posted. This works: 

```
@define-mixin buttonCommon {
  white-space: nowrap;
  padding: 0;
  height: var(--button-height);
  text-transform: uppercase;
  color: var(--color-white);
  background-color: var(--color-gray);
  border: none;

  transition-property: color, background-color, border, transform;
  transition-duration: var(--transition-duration-s);
  -webkit-tap-highlight-color: transparent;
  -webkit-appearance: none;


/*  &:focus {
    outline: none;
  }*/

 /* &:disabled {
    background: var(--color-gray);
    color: var(--color-white);
  }
*/
  width: 10em;
}
zzz

**Comment by MoOx** [comment]
Ok I think I get it. You probably need to run "postcss-mixins" before "postcss-cssnext" so postcss-nesting can convert selector correctly.

**Comment by 0x80** [comment]
Yes that was it! Thanks a lot for your help!
