### ISSUE TITLE
Vue2 + Webpack 2 + Cssnext Nesting not working (node.parent.after is not a function)

### ISSUE THREAD

**Issue by stablestorage** [jonathantneal/postcss-nesting#43]
I followed these steps: https://vue-loader.vuejs.org/en/features/postcss.html to integrate postcss with postcss-next including postcss-nesting to work.
When i try to write nested css in a scoped style of a component i get following error:

Module build failed: TypeError: node.parent.after is not a function
    at module.exports (/Users/valentin/projects/gymflow-redesign/node_modules/postcss-nesting/lib/transform-nesting-rule.js:18:29)
    at walk (/Users/valentin/projects/gymflow-redesign/node_modules/postcss-nesting/index.js:25:3)
    at walk (/Users/valentin/projects/gymflow-redesign/node_modules/postcss-nesting/index.js:33:4)
    at walk (/Users/valentin/projects/gymflow-redesign/node_modules/postcss-nesting/index.js:33:4)
    at LazyResult.run (/Users/valentin/projects/gymflow-redesign/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:274:20)
    at LazyResult.asyncTick (/Users/valentin/projects/gymflow-redesign/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:189:32)
    at LazyResult.asyncTick (/Users/valentin/projects/gymflow-redesign/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/Users/valentin/projects/gymflow-redesign/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/Users/valentin/projects/gymflow-redesign/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/Users/valentin/projects/gymflow-redesign/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/Users/valentin/projects/gymflow-redesign/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/Users/valentin/projects/gymflow-redesign/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:201:22)
    at processing.Promise.then._this2.processed (/Users/valentin/projects/gymflow-redesign/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:228:20)
    at Promise (<anonymous>)
    at LazyResult.async (/Users/valentin/projects/gymflow-redesign/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:225:27)
    at LazyResult.then (/Users/valentin/projects/gymflow-redesign/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:131:21)

 @ ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-788cdde0","scoped":true,"hasInlineConfig":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Hello.vue 4:14-326 13:3-17:5 14:22-334
 @ ./src/components/Hello.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

CSS: 
ul {
  list-style-type: none;
  padding: 0;
  display: flex;

  & li {
    display: inline-block;
    margin: 0 10px;
  }
}

.postcssrc.js:
module.exports = {
  plugins: {
    'postcss-cssnext': {},
    'autoprefixer': {},
    'cssnano': {}
  }
}

anyone else having this issue or suggestions to solve this?

**Comment by auser** [comment]
Has this been solved?
