### ISSUE TITLE
Cannot read property 'insertAfter' of undefined

### ISSUE THREAD

**Issue by AlexWayfer** [jonathantneal/postcss-nesting#58]
I even don't know what causes this.

```
TypeError: Cannot read property 'insertAfter' of undefined
    at Rule.after (/path/to/project/node_modules/postcss/lib/node.js:411:21)
    at module.exports (/path/to/project/node_modules/postcss-nesting/lib/transform-nesting-rule.js:18:29)
    at module.exports (/path/to/project/node_modules/postcss-nesting/lib/transform.js:16:3)
    at /path/to/project/node_modules/postcss/lib/container.js:144:26
    at AtRule.each (/path/to/project/node_modules/postcss/lib/container.js:110:22)
    at AtRule.walk (/path/to/project/node_modules/postcss/lib/container.js:143:21)
    at /path/to/project/node_modules/postcss/lib/container.js:146:32
    at Rule.each (/path/to/project/node_modules/postcss/lib/container.js:110:22)
    at Rule.walk (/path/to/project/node_modules/postcss/lib/container.js:143:21)
    at /path/to/project/node_modules/postcss/lib/container.js:146:32
error Command failed with exit code 1.
```

**Comment by jonathantneal** [comment]
I do not know what is causing this either. Could you share an isolated example of the code that does this? Perhaps something testable in https://preset-env.cssdb.org/playground ?

**Comment by AlexWayfer** [comment]
I can't reproduce this case. I'll reopen the issue if I find.
